BBS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views
from django.views.static import serve
from BBS import settings
from blog import urls as blog_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 登陆相关
    url(r'^login/', views.Login.as_view()),
    url(r'^login_huadong/', views.login_huadong),  # 滑动验证码
    url(r'^pcgetcaptcha/', views.pcgetcaptcha),
    url(r'^index/', views.Index.as_view()),
    url(r'^v_code/', views.v_code),
    # 注册相关
    url(r'^register/', views.Register.as_view()),
    # 给用户上传文件 配置一个处理的路由, 标准写法，就这么写
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),

    # 注销
    url(r'^logout/', views.log_out),

    # 个人博客站点
    url(r'^blog/', include(blog_urls)),

    # 点赞和返回
    url(r"^UpDown/", views.up_down),

    # 评论
    url(r'^comment/$', views.comment),  # 评论楼
    url(r'^comment_tree/(\d+)$', views.comment_tree),  # 评论树

    url(r'^$', views.Index.as_view()),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class UserInfo(AbstractUser):
    """
    用户信息
    """
    phone = models.CharField(max_length=11, unique=True, null=False)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png")  # 头像
    blog = models.OneToOneField(to="Blog", null=True)

    def __str__(self):
        return "UserInfo_obj_{}".format(self.username)

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """
    个人博客信息
    """
    title = models.CharField(max_length=64)  # 个人博客标题
    theme = models.CharField(max_length=32)  # 个人自定制博客主题

    def __str__(self):
        return "Blog_obj_{}".format(self.title)

    class Meta:
        verbose_name = "博客信息"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog")  # 外键关联博客，一个 个人博客站点 可以有多个文章分类

    def __str__(self):
        return "Category_obj_{}_{}".format(self.blog.title, self.title)

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog")  # 所属博客

    def __str__(self):
        return "Tag_obj_{}".format(self.title)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    title = models.CharField(max_length=50)
    desc = models.CharField(max_length=255)
    create_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(to="Category", null=True, blank=True)
    user = models.ForeignKey(to="UserInfo")
    tags = models.ManyToManyField(
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),
    )
    # 评论数
    comment_count = models.IntegerField(default=0)
    read_count = models.IntegerField(default=0)
    # 点赞数
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    def __str__(self):
        return "Article_obj_{}".format(self.title)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    content = models.TextField()  # 文章内容
    article = models.OneToOneField(to="Article")

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系
    """
    article = models.ForeignKey(to="Article")
    tag = models.ForeignKey(to="Tag")

    def __str__(self):
        return "Article2Tag_obj_{}_{}".format(self.article, self.tag)

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    user = models.ForeignKey(to="UserInfo", null=True)
    article = models.ForeignKey(to="Article", null=True)
    is_up = models.BooleanField(default=True)  # 点赞还是踩灭

    def __str__(self):
        return "ArticleUpDown_obj_{}-{}".format(self.user_id, self.article_id)

    class Meta:
        unique_together = (("article", "user"),)  # 同一个人只能给一篇文章点一次赞
        verbose_name = "点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论表
    """
    article = models.ForeignKey(to="Article")
    user = models.ForeignKey(to="UserInfo")
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)

    parent_comment = models.ForeignKey("self", null=True, blank=True)  # 自己关联自己

    def __str__(self):
        return "Comment_obj_{}".format(self.content)

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加新博客</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post">
            {% csrf_token %}
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="标题" >
                </div>
                <div class="form-group">
                    <label for="content">内容</label>
                    <textarea class="form-control" name="content" id="content" cols="30" rows="20"></textarea>
                </div>

                <div class="form-group">
                    <label for="category">文章分类</label>
                    <select name="category" id="category" class="form-control">
                        {% for category in category_list %}
                            <option value="{{ category.id }}">{{ category.title}}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-success">发布</button>
                <span style="color: red">{{ err_msg }}</span>
            </form>
        </div>
    </div>
</div>
<script src="/static/plugins/jquery-3.3.1.min.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor-master/kindeditor-all.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor-master/lang/zh-CN.js"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#content', {
                    "uploadJson": "/blog/upload/",
                    "extraFileUploadParams": {"csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val()}
                });
        });
</script>
</body>
</html>

templates/article.html
{% extends "base.html" %}

{% block show_article %}
    <div class="article-detail">
        <h4 class="media-heading article-title"><a
                href="/blog/{{ username }}/p/{{ article_obj.id }}">{{ article_obj.title }}</a></h4>
        <div class="article-content">{{ article_obj.articledetail.content|safe }}</div>
    </div>
    {% csrf_token %}
    <hr>
    <!-- 点赞 开始-->
    <div class="clearfix">
        <div id="div_digg">
            <!-- 点赞 -->
            <div class="diggit digg">
                <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
            </div>
            <!-- 反对 -->
            <div class="buryit digg">
                <span class="burynum" id="bury_count">{{ article_obj.down_count }}</span>
            </div>
            <div class="clear"></div>
            <!-- 提示信息 -->
            <div class="diggword clearfix" id="digg_tips"></div>
            <a href="/login/?next={{ request.path_info }}" style="display: none" id="go-login">去登陆</a>
        </div>
    </div>
    <!-- 点赞 结束-->

    <!-- 展示评论开始 -->
    <div class="comment-bar">
        评论列表
    </div>
    <div class="list-group all-comment">
        {% for comment_obj in comment_obj_list %}
            <div class="list-group-item comment-list" my_id="{{ comment_obj.id }}">
                <div class="list-group-item-heading">
                    <span>#{{ forloop.counter }}楼</span>
                    <span>{{ comment_obj.create_time|date:'Y-m-d H:i' }}</span>
                    <span><a href="/blog/{{ comment_obj.user.username }}">{{ comment_obj.user.username }}</a></span>
                    <span class="pull-right replay">回复</span>
                </div>
                {% if comment_obj.parent_comment %}
                    <span>@{{ comment_obj.parent_comment.user.username }}</span>
                {% endif %}
                <p class="list-group-item-text comment-content">{{ comment_obj.content }}</p>
                <div class="clearfix">
                    <div class="comment-up-down pull-right">
                        <a href="">支持(0)</a>
                        <a href="">反对(0)</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="pull-right">
        <a href="#">刷新评论</a>
        <a href="/blog/{{ username }}/p/{{ article_obj.id }}">刷新页面</a>
        <a href="#top">返回顶部</a>
    </div>
    <!-- 展示评论结束 -->

    <!-- 发表评论开始 -->
    <div class="comment-container">
        <div class="comment-bar">发表评论</div>
        <div>
            昵称：
            <input type="text" value="{{ request.user.username }}" disabled>
        </div>
        <div>
            <p class="neirong">评论内容：</p>
            <textarea id="new-comment" cols="60" rows="10"></textarea>
        </div>
        <div>
            <button class="btn btn-success submit-comment">提交评论</button>
        </div>
    </div>
    <!-- 发表评论结束 -->

{% endblock show_article %}

{% block UpDown-js %}
    <script type="text/javascript">
        $(function () {
            $(".digg").click(function () {
                if (!'{{request.user.username}}') {
                    $("#digg_tips").text("没有登陆，不能点赞或者反对");
                    $("#go-login").css("display", "block");
                    {#location.href = "/login/?next={{ request.path_info }}"#}
                }
                let userId = '{{ request.user.id }}';
                let articleId = '{{ article_obj.id }}';
                let isUp = $(this).hasClass("diggit");
                $.ajax({
                    url: "/UpDown/",
                    type: "post",
                    data: {
                        csrfmiddlewaretoken: $("[name=csrfmiddlewaretoken]").val(),
                        userId: userId,
                        articleId: articleId,
                        isUp: isUp
                    },
                    success: function (res) {
                        if (res.code !== 0) {
                            // 只需要把错误提示显示出来就可以
                            $("#digg_tips").text(res.msg);
                        } else {
                            // 1. 先把点赞数或反对数更新一下
                            if (isUp) {
                                // 表示更新点赞数
                                let $digg_count = $("#digg_count");
                                // 注意拿到的是内容是字符串，不能直接加+1，需要先转数字
                                {#console.log($digg_count.text(), typeof $digg_count.text());#}
                                // 方式1
                                $digg_count.text(+$digg_count.text() + 1);
                                // 方式2
                                {#$digg_count.text(parseInt($digg_count.text())+1)#}
                            } else {
                                // 表示更新反对数
                                let $bury_count = $("#bury_count");
                                $bury_count.text(+$bury_count.text() + 1)
                            }
                            // 2. 再显示提示
                            $("#digg_tips").text(res.msg);
                        }
                    }
                })
            });
            $(".submit-comment").click(function () {
                var user_id = '{{ request.user.id }}';
                var article_id = '{{ article_obj.id }}';
                var content = $("#new-comment").val();
                // 这里的父id是从下方自己存储进去的，在这里可以拿出来使用
                var parent_id = $(this).data("pid") || "";
                // 也有可能没点回复，直接添加的父评论，所以这里需要写上 || (或者""),防止报错
                if (parent_id) {
                    // 如果父id存在，需要把评论内容中的 @xx去掉
                    // 使用”\n"的索引，切片拿到真正的评论
                    content = content.slice(content.indexOf("\n") + 1,);
                }
                // var content = (parent_id)? content.slice(content.indexOf("\n") + 1,):content;  三元运算符的写法
                $.ajax({
                    url: '/comment/',
                    type: 'post',
                    data: {
                        user_id: user_id,
                        article_id: article_id,
                        content: content,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                        parent_id: parent_id
                    },
                    success: function (res) {
                        console.log(res);
                        if (res.code === 0) {
                            var num = $(".all-comment>div").length + 1;
                            var commentHtml = `
                                <div class="list-group-item comment-list" my_id=${ res.data.parent_id}>
                                    <div class="list-group-item-heading">
                                        <span>#${num}楼</span>
                                        <span>${res.data.create_time}</span>
                                        <span><a href="/blog/${ res.data.username }">${ res.data.username }</a></span>
                                        <span class="pull-right replay">回复</span>
                                    </div>
                                    <p class="list-group-item-text comment-content">${ res.data.new_content }</p>
                                    <div class="clearfix">
                                        <div class="comment-up-down pull-right">
                                            <a href="">支持(0)</a>
                                            <a href="">反对(0)</a>
                                        </div>
                                    </div>
                                </div>`;
                            $(".all-comment").append(commentHtml);
                            // 清空textarea内容
                            $("#new-comment").val("");
                            // 不要忘记使用完之后 删除，要不然每次评论都能拿到父id
                            $(".submit-comment").removeData("parent_id")
                        }
                    }
                })

            });
            // 给回复按钮绑定事件
            {#$(".replay").click(function () {#} // 这种不可以，新添加的评论没有点击事件
            // 需要使用事件绑定
            $(".all-comment").on("click", ".replay", function () {
                // 1. 光标聚焦到评论框
                // 2. 添加一个@xxx的提示
                var replayName = $(this).prev().text();
                {#console.log(replayName);#}
                $("#new-comment").focus().val("@" + replayName + "\n");
                // 这里需要注意的是：
                // 我们在每一条评论上添加了自定义属性，方便我们拿到父评论id，
                // 但是我们用这个父id是要发送的后端去，后端存在数据库中，
                // 而和后端交互的时候是在发表评论的提交按钮（ $(".submit-comment")）是触发的，
                // 但是在提交按钮中，是没办法拿到是点击的那个 回复 事件，也就没法拿到父id；
                // 所以在js中有个方法，可以将数据保存在某个jquery对象中，如下data方法
                var pID = $(this).parent().parent().attr("my_id");
                $(".submit-comment").data("pid", pID);
            })
        });

    </script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/bbs_css.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>
<!--导航栏开始-->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/login/"><button class="btn btn-success btn-sm">登陆</button></a>
                </li>
                <li>
                    <a href="/register/"><button class="btn btn-info btn-sm">注册</button></a>
                </li>
{#                <li><a href="/blog/">{{ request.user.username }}</a></li>#}
{#                <li>#}
{#                    <img src="/media/{{ request.user.avatar }}" alt="" style="height: 50px;width: 50px;border-radius: 50%">#}
{#                </li>#}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!--导航栏结束-->

<!--主题内容开始-->
<div class="container-fluid">
    <div class="row">
        <!-- 左侧广告栏开始 -->
        <div class="col-md-2">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <!-- 左侧广告栏结束 -->

        <!-- 中间内容开始 -->
        <div class="col-md-8">
            <div class="article-list">
                {% for article in article_list %}
                    <div class="article">
                        <div class="media">
                            <h3><a class="media-heading media-title" href="#">{{ article.title }}</a></h3>
                            <div class="media-left">
                                <a href="/blog/{{ article.user.username }}">
                                    <img class="media-object media-avatar" src="/media/{{ article.user.avatar }}"
                                         alt="...">
                                </a>
                            </div>
                            <div class="media-body">
                                <div class="article-desc">
                                    {{ article.desc }}&nbsp;...
                                </div>
                            </div>
                            <div class="article-footer">
                                <span><a href="/blog/{{ article.user.username }}">{{ article.user.username }}</a></span>
                                <span>&nbsp;发布于&nbsp;{{ article.create_time|date:"Y-m-d H:i:s" }}</span>
                                <span>
                                    <!--
{#                                    {{ article.comment_set.all.count }} 这样是跨表查询，不好，可以在文章表里自定义字段，做一个事务性操作，不跨表查询#}
                                    <a href="">
{#                                        <i class="fa fa-commenting-o fa-lg" aria-hidden="true"></i>评论({{ article.comment_set.all.count }})#}
                                    </a>
                                    -->
                                    <a href="">
                                        <i class="fa fa-commenting-o fa-lg" aria-hidden="true"></i>评论({{ article.comment_count }})
                                    </a>
                                </span>
                                <span>
                                     <!--
{#                                     {{ article.articleupdown_set.all.count }} 这样是跨表查询，不好，可以在文章表里自定义字段，做一个事务性操作，不跨表查询}#}
                                    <a href="">
{#                                        <i class="fa fa-thumbs-up fa-lg" aria-hidden="true"></i>点赞({{ article.articleupdown_set.all.count }})#}
                                    </a>
                                    -->
                                    <a href="">
                                        <i class="fa fa-thumbs-up fa-lg" aria-hidden="true"></i>点赞({{ article.up_count }})
                                    </a>
                                </span>
                            </div>

                        </div>
                    </div>
                    <hr>
                {% endfor %}
            <div class="my-page">
               {{ page_html|safe }}
            </div>

            </div>
        </div>
        <!-- 中间内容结束 -->

        <!-- 右侧广告栏开始 -->
        <div class="col-md-2">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <!-- 右侧广告栏结束 -->
    </div>
</div>
<!--主题内容结束-->

<script src="/static/plugins/jquery-3.3.1.min.js"></script>
<script src="/static/plugins/bootstrap-3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/bbs_css.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>
{% csrf_token %}
<div class="container top">
    <div class="row">
        <form class="form-horizontal" novalidate>
            <div class="form-group">
                <label for="{{ form_obj.username.id_for_label }}" class="col-sm-2 col-sm-offset-2 control-label">{{ form_obj.username.label }}</label>
                <div class="col-sm-4">
                    {{ form_obj.username }}
                    <span class="help-block"></span>
                </div>
            </div>

            <div class="form-group">
                <label for="{{ form_obj.password.id_for_label }}" class="col-sm-2 col-sm-offset-2 control-label">{{ form_obj.password.label }}</label>
                <div class="col-sm-4">
                    {{ form_obj.password }}
                    <span class="help-block"></span>
                </div>
            </div>

            <div class="form-group">
                <label for="{{ form_obj.re_password.id_for_label }}" class="col-sm-2 col-sm-offset-2 control-label">{{ form_obj.re_password.label }}</label>
                <div class="col-sm-4">
                    {{ form_obj.re_password }}
                    <span class="help-block"></span>
                </div>
            </div>

            <div class="form-group">
                <label for="{{ form_obj.phone.id_for_label }}" class="col-sm-2 col-sm-offset-2 control-label">{{ form_obj.phone.label }}</label>
                <div class="col-sm-4">
                    {{ form_obj.phone }}
                    <span class="help-block"></span>
                </div>
            </div>

            <div class="form-group">
                <label for="{{ form_obj.email.id_for_label }}" class="col-sm-2 col-sm-offset-2 control-label">{{ form_obj.email.label }}</label>
                <div class="col-sm-4">
                    {{ form_obj.email }}
                    <span class="help-block"></span>
                </div>
            </div>

            <div class="form-group">
                <label for="avatar" class="col-sm-2 col-sm-offset-3 control-label">头像
                    <img id="avatar-img" src="/static/img/default.png" alt="" style="height: 80px;width: 80px;margin-left: 20px">
                </label>
                <div class="col-sm-4">
                    <input type="file" accept="image/*" id="avatar" style="display: none;">
                </div>
            </div>

            <div class="form-group">
                <label for="v-code" class="col-sm-2 col-sm-offset-2 control-label">验证码</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" id="v-code" placeholder="验证码" style="display: inline-block">
                    <span id="error-msg" style="color: red"></span>
                </div>
                <div class="col-sm-2">
                    <img src="/v_code/" id="random_img" alt="" style="height: 34px; width: 170px;">
                    <i class="fa fa-refresh fa-2x" id="refresh" aria-hidden="true" style="cursor: pointer"></i>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-4">
                    <button type="button" class="btn btn-success btn-lg btn-block" id="reg_btn">注册</button>
                </div>
            </div>

        </form>
    </div>
</div>
<script src="/static/plugins/jquery-3.3.1.min.js"></script>
<script>
    $(function () {

        /*  不上传头像的写法
        $("#reg_btn").click(function () {
            let username = $("#id_username").val();
            let pwd = $("#id_password").val();
            let re_pwd = $("#id_re_password").val();
            let phone = $("#id_phone").val();
            let email = $("#id_email").val();
            let csrfToken = $("[name='csrfmiddlewaretoken']").val();
            let v_code = $("#v-code").val();
            $.ajax({
                url: "/register/",
                type: "post",
                data:{
                    username: username,
                    password: pwd,
                    re_password: re_pwd,
                    phone: phone,
                    email: email,
                    v_code:v_code,
                    'csrfmiddlewaretoken': csrfToken
                },
                success: function (res) {
                    if(res.code === 0){
                        location.href = res.msg
                    }else if(res.code === 1){
                        console.log(res.msg);
                        // 遍历取出所有的错误提示信息，在页面上展示出来
                        $.each(res.msg, function (k, v) {
                            $("#id_"+k).next().text(v[0]).parent().addClass("has-error");
                        })
                    }else{
                        // 验证码正确
                        $("#error-msg").text(res.msg)
                    }
                }
            })
        });
        */

        // 加上上传头像
        $("#reg_btn").click(function () {
            // 创建一个FormData对象
            let obj = new FormData();
            // 将要上传的文件数据添加到对象中
            obj.append("avatar", $("#avatar")[0].files[0]);

            // 也可添加其他内容
            obj.append("username", $("#id_username").val());
            obj.append("password", $("#id_password").val());
            obj.append("re_password", $("#id_re_password").val());
            obj.append("phone", $("#id_phone").val());
            obj.append("email", $("#id_email").val());
            obj.append("v_code", $("#v-code").val());
            obj.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());


            $.ajax({
                url: "/register/",
                type: "post",
                data:obj,
                processData: false, // 不让jQuery处理我的obj
                contentType: false, // 不让jQuery设置请求的内容类型
                success: function (res) {
                    if(res.code === 0){
                        // 注册成功跳转登陆页面
                        location.href = res.msg
                    }else if(res.code === 1){
                        {#console.log(res.msg);#}
                        // 遍历取出所有的错误提示信息，在页面上展示出来
                        $.each(res.msg, function (k, v) {
                            $("#id_"+k).next().text(v[0]).parent().addClass("has-error");
                        })
                    }else{
                        // res.code === 2
                        // 验证码错误
                        $("#error-msg").text(res.msg)
                    }
                }
            })
        });



        $("#refresh").click(function () {
            let img_src = document.getElementById("random_img");
            // 方式1
            // img_src.src += "?"; 这个方式每次都加url，不好看

            // 方式2
           // 使用正则验证，url,如果以？结尾,就切片去掉，没有？，就加一个？，达到每次url不同的目的，去刷新v_code
            // 但是记得后端加django装饰器，保证每次都重新请求，不使用缓存
            let url = img_src.src;
            if (/\?$/.test(url)){
                img_src.src = url.slice(0, -1);
            }else{
                img_src.src = url + "?";
            }
        });

        // 每一个input标签获取焦点的时候，把自己下面的span标签内容清空，把父标签的has-error样式移除
        $("input.form-control").focus(function () {
            $(this).next("span").text("").parent().removeClass("has-error");
        });

        // 前端页面实现头像预览
        // 当用户选中文件之后，也就是头像的input标签有值时触发
        $("#avatar").change(function () {
            // 找到用户选中的那个文件
            let file = this.files[0];
            // 生成一个读文件的对象
            let fr = new FileReader();
            // 从文件中读取头像文件数据
            fr.readAsDataURL(file);
            // 等到读完之后,加载需要时间
            fr.onload = function () {
                // 将头像img标签的src属性更换成我选中的那个文件
                $("#avatar-img").attr("src", fr.result)
            }
        })

    });
</script>

</body>
</html>